/*
 * This file is generated by jOOQ.
 */
package com.exercise.generator;


import com.exercise.generator.tables.Author;
import com.exercise.generator.tables.Book;
import com.exercise.generator.tables.BookStore;
import com.exercise.generator.tables.BookToBookStore;


/**
 * Convenience access to all tables in test
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>test.book</code>.
     */
    public static final Book BOOK = Book.BOOK;

    /**
     * The table <code>test.book_store</code>.
     */
    public static final BookStore BOOK_STORE = BookStore.BOOK_STORE;

    /**
     * The table <code>test.book_to_book_store</code>.
     */
    public static final BookToBookStore BOOK_TO_BOOK_STORE = BookToBookStore.BOOK_TO_BOOK_STORE;
}
