/*
 * This file is generated by jOOQ.
 */
package com.exercise.generator;


import com.exercise.generator.tables.Author;
import com.exercise.generator.tables.Book;
import com.exercise.generator.tables.BookStore;
import com.exercise.generator.tables.BookToBookStore;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test extends SchemaImpl {

    private static final long serialVersionUID = -324046750;

    /**
     * The reference instance of <code>test</code>
     */
    public static final Test TEST = new Test();

    /**
     * The table <code>test.author</code>.
     */
    public final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>test.book</code>.
     */
    public final Book BOOK = Book.BOOK;

    /**
     * The table <code>test.book_store</code>.
     */
    public final BookStore BOOK_STORE = BookStore.BOOK_STORE;

    /**
     * The table <code>test.book_to_book_store</code>.
     */
    public final BookToBookStore BOOK_TO_BOOK_STORE = BookToBookStore.BOOK_TO_BOOK_STORE;

    /**
     * No further instances allowed
     */
    private Test() {
        super("test", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Author.AUTHOR,
            Book.BOOK,
            BookStore.BOOK_STORE,
            BookToBookStore.BOOK_TO_BOOK_STORE);
    }
}
